### ISSUE TITLE
本身rxjava里面就有防抖动接口

### ISSUE THREAD

**Issue by luxiaoming** [SmartDengg/RxDebounceClick#1]

**Comment by SmartDengg** [comment]
哪个接口呢？

**Comment by luxiaoming** [comment]
RxTextView.textChangeEvents(inputEditText)  
      .debounce(400, TimeUnit.MILLISECONDS)  
      .observeOn(AndroidSchedulers.mainThread())  
      .subscribe(new Observer<TextViewTextChangeEvent>() {  
    @Override  
    public void onCompleted() {  
        log.d("onComplete");  
    }  

```
@Override  
public void onError(Throwable e) {  
    log.d("Error");  
}  
```

**Comment by luxiaoming** [comment]
.debounce( 这个函数本身自带的

**Comment by SmartDengg** [comment]
为什么.debounce()里面要传入400？

**Comment by luxiaoming** [comment]
自己去写，一般是150

**Comment by SmartDengg** [comment]
为什么是150？经验值吗？

**Comment by luxiaoming** [comment]
经验值

**Comment by SmartDengg** [comment]
如何得出的此经验值呢？能否分享一下你的看法？

**Comment by luxiaoming** [comment]
这个值就是测试出来的，统计下来会误触发双击的临界时间点。你自己可以去测试你快速点击时间，看下误触发的时间间隙就知道这个值怎么来的了。

**Comment by SmartDengg** [comment]
我想这个阈值的裁定，取决于下层消费者的消费能力，并不能单纯的通过测试得出。

**Comment by luxiaoming** [comment]
看这个是防抖动的，跟消费有什么关系。你告诉我下消费时间能确定？你能知道消费消耗多长时间。  不讨论了。

**Comment by SmartDengg** [comment]
你首先也应该去了解一下[Backpressure](https://github.com/ReactiveX/RxJava/wiki/Backpressure)吧，只是单纯地从RxJava的操作符去理解问题必然不能从根本上解决。既然你都这么说，看来你既不懂[debounce](http://reactivex.io/documentation/operators/debounce.html)也不懂**[RxJava](https://github.com/ReactiveX/RxJava/wiki)**，不想讨论的话，我就把这个issue关闭了！

**Comment by luxiaoming** [comment]
不懂，结束吧。自己直接去看代码吧。

**Comment by luxiaoming** [comment]
我改变下态度，debounce在你指定时间内阻止相同消息，没有消息过来就触发消费此消息。如此就可以阻止因为你的抖动误操作触发两次响应。看清问题在说抖动。说的是你的无意会触发的两次点击事件。

**Comment by SmartDengg** [comment]
:)
